version: '3.1'
services:
  pgsql:
    container_name: pgsql
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ADMIN_PASS}
      POSTGRES_USER: root
    ports:
      - "5432:5432"