name: Run Tests on Push

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start PostgreSQL Container
      env:
        PGSQL_ADMIN_PASS: 1a2b3c4d5e!$
        PGSQL_VOLUME: ./pgsql_data
        PGSQL_PORT_MAPPING: 5432:5432
      run: |
        docker-compose -f docker/db.docker-compose.yml up -d
        for i in {1..30}; do
          if docker exec pgsql pg_isready -U root > /dev/null 2>&1; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        docker exec -u postgres pgsql psql -c "CREATE DATABASE test_db;" -U root


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Set DATABASE_URL environment variable
      run: echo "DATABASE_URL=postgresql://root:1a2b3c4d5e%21@localhost:5432/test_db" >> $GITHUB_ENV

    - name: Run Tests
      env:
        FLASK_ENV: testing
        DATABASE_URL: ${{ env.DATABASE_URL }}
      run: |
        pytest --maxfail=2 --disable-warnings
